bonfire/bonfire.py, bonfire/openshift.py
* Adds an exit(1) if Bonfire times out waiting for resources
``` bash
15:06:11 INFO:bonfire.openshift:[deploy/ingress] Waiting for deployment "ingress" rollout to finish: 0 of 1 updated replicas are available...
15:06:11 INFO:bonfire.openshift:[deploy/env-ephemeral-04-minio] is ready!
15:11:11 ERROR:bonfire.openshift:[deploy/ingress] timed out waiting for resource to be ready
15:11:11 INFO:bonfire.openshift:Some resources failed to become ready: deploy/ingress
15:11:11 INFO:bonfire.openshift:Waiting for resources owned by 'ClowdApp' to appear
15:11:12 ERROR: Timed out waiting for resources; exiting
15:11:12 bonfire namespace release ephemeral-04
15:11:12 ++ bonfire namespace release ephemeral-04
```
=> Exit on timeout expiration

cicd/smoke_test.sh
needed for iqe env_parser
```
ValueError: ClowderEnvParser invoked but no 'namespace' given. Set NAMESPACE in env or set conf.VALUE_GETTERS.env_parser.namespace
```
=> Add NAMESPACE env var to iqe pod

bonfire/local_config.py
`bonfire local get --get-dependencies` fails when ClowdApp has dependencies because `processed_apps` is passed instead of `set_image_tag`
If I understood the code correctly `set_image_tag` is only used for `app` not for its `dependencies`. That's why I set it to `[]`
=> Fix missing set_image_tag argument

cicd/iqe_pod/iqe_runner.sh
when `IQE_MARKER_EXPRESSION` is empty, the marker is ` -m 'not parallel and ()'`, which throws error
```
ERROR: Wrong expression passed to '-m': not parallel and (): at column 19: expected not OR left parenthesis OR identifier; got right parenthesis
```
=> Fix empty marker expression

cicd/deploy_ephemeral_env.sh
NAMESPACE env is needed in teardown to collect logs and release reserved namespace even when deploy fails
why was namespace exported only when deploy succeeded? I hope that bonfire is returning exit code other than 0 when deploy fails (and jenkins stops), so removing this code won't break anything
```bash
if [ $? -eq 0 ]; then
export NAMESPACE=$result
fi
```
=> Set NAMESPACE when deploy fails

README.md
This adds some missing steps for running qontract-server locally. It may be obvious to a regular JS dev, but it took me a bit to figure out. 🤷🏻‍♂️
=> Update local qontract-server steps

bonfire/bonfire.py
This removes the misleading `-t` short flag for `--set-template-ref`. Because`timeout` already defines this flag, `-t` gets interpreted as `timeout` instead.
The `<app>/<component>=<ref>` syntax is also deprecated according to a further log message, so this updates the help text for this option as well.
=> Remove duplicate short flag

bonfire/bonfire.py, bonfire/config.py
:warning: First off: I am not a python programmer so this might be completely wrong. Roast me at your discretion!
I found myself wanting to immediately run `bonfire config edit` after running `bonfire config write-default` the first time - so I went ahead and added it here. I can't get it to quite run locally (somethign somethign `Starting path not found`), but from the looks of the `write-default` subcommand this might do the trick.
=> Add `bonfire config edit` command for easy editing of local config

bonfire/bonfire.py
Its a just cosmetic thing, but it was obvious and needed fixing (IMO).
Before patch:
```
(bonfire_venv) [mhuth@mhuth-laptop bonfire]$ bonfire deploy --help | egrep -- '--namespace|--target-env'
-n, --namespace TEXT            Namespace you intend to deploy to (default:
--target-env TEXT               When using source=appsre, name of
--target-env TEXT               When using source=appsre, name of
-n, --namespace TEXT            Namespace to deploy to (if none given,
(bonfire_venv) [mhuth@mhuth-laptop bonfire]$ bonfire process --help | egrep -- '--namespace|--target-env'
-n, --namespace TEXT            Namespace you intend to deploy to (default:
--target-env TEXT               When using source=appsre, name of
--target-env TEXT               When using source=appsre, name of
```
After: …
=> Remove duplicate options from process and deploy

bonfire/resources/ephemeral-clowdenvironment.yaml
Currently, people have to [dig through the clowder code](https://github.com/RedHatInsights/clowder/blob/e472159f10077105a4c9c83e26c87c0bce712b26/controllers/cloud.redhat.com/providers/web/default.go#L24) to figure out what this private web port is. We should instead make it explicit by setting it here in the default ClowdEnv.
=> Explicitly set the private web port to 10000

bonfire/bonfire.py, bonfire/processor.py, cicd/_common_deploy_logic.sh, cicd/deploy_ephemeral_db.sh, cicd/deploy_ephemeral_env.sh
- use --remove-resources/--no-remove-resources with argument e.g. `--remove-resources all --no-remove-resources vmaas --no-remove-resources something-else`
- don't allow to use `--remove-resources all --no-remove-resources all`
- `COMPONENTS_W_RESOURCES`env var for PR check to set which components should respect resources settings from clowdapp
- **it's a breaking change** - `--remove-resources/--no-remove-resources` expects 1 argument
=> RHCLOUD-14977 --no-remove-resources for specific components

bonfire/utils.py
While calling `--set-parameter`, I hit an issue when my `<value>` contains an `=` sign. This PR updates `split_equals` to split at most 1 time.
```python
>>> import re
>>> equals_regex = re.compile(r"^\S+=[\S ]+$")
>>> s = "<component>/<param>=<valuewithan=>"
>>> not equals_regex.match(s)
False
>>> key, val = s.split("=")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: too many values to unpack (expected 2)
>>> key, val = s.split("=", 1)
>>> key
'<component>/<param>'
>>> val
'<valuewithan=>'
```
=> split on first equals

bonfire/openshift.py
Fixes #95 
Adds a small helper function to check with `oc status` the existing K8s cluster session. This mainly happens on the `get_namespaces` action, which is the entrypoint for most of the actions related with the `deploy` action, so I think it makes sense to do it right there, but maybe is required elsewhere, some input is welcome :)
=> Add check against invalid cluster session

cicd/bootstrap.sh
https://setuptools.readthedocs.io/en/latest/history.html#v58-0-2
2to3 parameters used in some dependencies start to break build pipelines
=> temporary pin down setuptools 58.x for breaking

cicd/deploy_ephemeral_db.sh, cicd/deploy_ephemeral_env.sh
Removes deprecated syntax used on cicd helper scripts for `set-template-ref` parameter
=> Update set-template-ref syntax on helper scripts

bonfire/openshift.py
`_pod_found` return `False` not `None`. I think the `fail_condition` is not needed at all
```
15:12:53 2021-09-17 13:05:17 [    INFO] [          MainThread] waiting for Job to appear owned by CJI 'vmaas-smoke-tests'
15:12:53 2021-09-17 13:05:18 [    INFO] [          MainThread] found Job 'vmaas-smoke-tests-iqe' created by CJI 'vmaas-smoke-tests', now waiting for pod to appear
15:12:53 2021-09-17 13:05:18 [    INFO] [          MainThread] found pod 'False' associated with CJI 'vmaas-smoke-tests', now waiting for pod to be 'running'
15:12:53 2021-09-17 13:05:18 [   ERROR] [          MainThread] hit unexpected error!
15:12:53 Traceback (most recent call last):
15:12:53   File "/var/lib/jenkins/workspace/RedHatInsights-vmaas-pr-check/.bonfire_venv/lib64/python3.6/site-packages/bonfire/bonfire. …
```
=> Remove fail_condition while waiting for pod

cicd/iqe_pod/create_iqe_pod.py
Fix:
```
Error from server (Forbidden): error when creating "STDIN": pods "iqe-tests" is forbidden: memory max limit to request ratio per Pod is 2, but provided ratio is 4
```
=> Memory max limit to request ratio per Pod is 2

cicd/bootstrap.sh, cicd/build.sh
If we detect the scripts are running as part of a Jenkins job for a PR, we will tag the image as `pr-<pr id>-<first 7 chars of commit sha>`
=> Tag PR images differently to prevent accidental prod deploy

cicd/_common_deploy_logic.sh
`KEEP_NAMESPACE` is unset or empty string -> release namespace
`KEEP_NAMESPACE` set to anything else -> set it to `TRUE` and keep namespace
it would be useful for debugging failing PR checks
=> Keep namespace after test run with with RELEASE_NAMESPACE=false

bonfire/namespaces.py
when ns operator is not working properly it can happen that it returns ns with name `''`
```
{'apiVersion': 'cloud.redhat.com/v1alpha1',
'kind': 'NamespaceReservation',
'metadata': {'annotations': {'kubectl.kubernetes.io/last-applied-configuration': '{"apiVersion":"cloud.redhat.com/v1alpha1","kind":"NamespaceReservation","metadata":{"annotations":{},"labels":{"requester":"psegedy"},"name":"bonfire-reservation-508bc141"},"spec":{"duration":"1h","requester":"psegedy"}}\n'},
'creationTimestamp': '2022-01-13T14:58:50Z',
'generation': 1,
'labels': {'requester': 'psegedy'},
'name': 'bonfire-reservation-508bc141',
'resourceVersion': '644150572',
'uid': '69fab39b-824d-412a-a626-6b7207f10d58'},
'spec': {'duration': '1h', 'requester': 'psegedy'},
'status': {'expiration': '2022-01-13T15:58:50Z', …
```
=> fail with FatalError if reserved ns is empty string

cicd/build.sh
Add an env var to allow the Quay expiration time to be adjustable for PR images.
This can provide an extended time frame to test major feature PRs in an ephemeral environment prior merging into the default branch.
=> allow pr image expiration to be adjustable

cicd/examples/pr_check_template.sh, cicd/post_test_results.sh
The result of this change is demonstrated here https://github.com/RedHatInsights/drift-backend/pull/332#issuecomment-1094599435
The idea is that the following line is added to `pr_check.sh` after calling `cji_smoke_test.sh`
```
source $CICD_ROOT/post_test_results.sh
```
The link to Ibutsu is hidden according to the recommendation https://url.corp.redhat.com/4ebe1ab therefore not possible to make it dynamic (include the id in the URL).
=> add a script to post test run IDs

cicd/post_test_results.sh
This is a modification for a `post_test_results.sh` script. It adds posting a comment to GitLab MR.
Tested in GitHub PR: https://github.com/RedHatInsights/drift-backend/pull/332
Tested in GitLab MR: https://url.corp.redhat.com/85cbec6
=> post comment for gitlab MR

cicd/post_test_results.sh
If the repo name contains spaces, the link to post a comment becomes broken. Spaces are replaced with dashes.
Tested here https://url.corp.redhat.com/cf5d9b8
=> replace spaces with dashes for the gitlab comment

bonfire/bonfire.py, bonfire/namespaces.py, bonfire/openshift.py, tests/data/namespace_data.json, tests/test_bonfire.py
- Switched "status" label to "env-status"
- get_all_namespaces() function filters by newly created label: "operator-ns"
- Added property for the Namespaces class in namespaces.py to get label.
- Removed "operator-ns" annotation.
=> Rhcloud 18846 use new labels annotations

cicd/post_test_results.sh
Works for GH: https://github.com/RedHatInsights/drift-backend/pull/340
For some reason pr_check didn't run in advisor repo yet, so not tested there
=> unify the message for GH and GL

cicd/post_test_results.sh
Unfortunately the iteration is a bit tricky in shell, and it didn't work properly when there was more than one result. 
This is the fix and it was verified here https://github.com/RedHatInsights/playbook-dispatcher/pull/245
=> fix iteration over uuids in post_test_results.sh

cicd/README.md, cicd/bootstrap.sh, cicd/build.sh
Within build.sh, construct `IMAGE_TAG_OPTS`
- In the case of a PR, use `pr-123-SHA` and `pr-123-latest` tags
- Docker push with --all-tags
- podman push twice
https://issues.redhat.com/browse/RHCLOUD-20838
Tested alongside this repo:
https://github.com/content-services/content-sources-backend/pull/82/files
Pipeline run:
https://ci.int.devshift.net/job/content-services-content-sources-backend-pr-check/82/console 
Resulting images:
=> Add a secondary tag for PR/MR image builds

bonfire/bonfire.py, bonfire/qontract.py, bonfire/utils.py
Add a simple network connetion check to see if we can reach internal resources.
If we're using the appSRE source and can't get a DNS response for gitlab, we error out.
This is to keep bonfire from hanging when not connected to the VPN as listed in RHCLOUD-21617
---
Add a check_connection function to error out if we cant' reach required
sources when running bonfire. Without this we hang for a very long time.
This also adds a message to inform the user to check their VPN
connection.
RHCLOUD-21617
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>
=> feat: Error out if using appSRE source and not on internal network

bonfire/bonfire.py, bonfire/openshift.py
If the user is piping their output somewhere other than stdout, then we shouldn't prompt them for input. 
I thought about moving the prompt and then switching back to the previous output, but I think it's better to go ahead and error out and let them re-run the command with `-f` or use the namespace they already have.
RHCLOUD-20009
=> Do not prompt a user for input when not outputting to a tty

bonfire/utils.py, pyproject.toml, setup.py
- Removes pin to specific setuptools version (**resources** dir seems to be fine, WRT comment in 005883122bed8c72b7e60cb4cc424b293eb9d05b)
- Removes `tests` from wheel to avoid them being distributed
- Refactor `setuptools_scm` and `setuptools` config sections to not to require setup.py
- Replace usage of `pkg_resources` with `importlib.metadata` for calculating `version`
=> Update to latest setuptools, refactor project config

bonfire/bonfire.py, bonfire/namespaces.py, bonfire/openshift.py, setup.cfg, tests/test_bonfire.py
**Needs testing**
Use namespace from current context for majority of bonfire commands,
making the --namespace optional.
The deploy command tries to use current namespace, and if it is not
reserved or not owned it reserves a new one.  This is to keep backwards
compatiblity.
On each reservation a new namespace is set on current (or appropriate) context.
Adds --reserve option to deploy command to force a reservation of new
namespace.
=> Optional namespace

cicd/bootstrap.sh
When invoking pip directly, I was seeing errors in the Jenkins job. When I switched to invoking with `python3 -m pip` I was able to get beyond my errors. It sounds like this is the recommended way to invoke pip now, so I'd advocate for adopting this in bootstrap.sh unless there are reasonable objections.
=> Invoke pip with `python3 -m pip`

cicd/build.sh
This restores the behavior changed with #286 , as it brought up the issue describe in #291, as no new layers are added during PR/MR runs since the Dockerfile was not modified.
until #291 is sorted out, I'm adding back the "modify Dockerfile functionality" since it avoids `podman` to wrongly associate the expiry labels to release images.
=> Restore adding expiry label to Dockerfile

cicd/bootstrap.sh
- Fixes bug when sourcing dotfiles using relative paths on `sh` shells
- Adds variables to overwrite the Org and the branch from where the bootstrap script is pulled for debugging purposes.
=> Path fix for sh

bonfire/utils.py
This patch adds a type check on the response object when we get a SHA. it can sometimes be a list rather than a dict. 
We got this report and this should fix it:
```
2023-08-24 14:22:41 [   ERROR] [          MainThread] failed to fetch template file for service-accounts
2023-08-24 14:22:41 [   ERROR] [          MainThread] hit fatal error: list indices must be integers or slices, not str
2023-08-24 14:22:41 [    INFO] [          MainThread] releasing namespace 'ephemeral-x0cun8'
2023-08-24 14:22:42 [    INFO] [          MainThread] processing namespace reservation
2023-08-24 14:22:42 [    INFO] [          MainThread] running (pid 95686): oc apply -f -
2023-08-24 14:22:43 [    INFO] [           pid-95686]  |stdout| namespacereservation.cloud.redhat.com/bonfire-reservation-cf86f0d8 …
```
=> Type check SHA response

bonfire/resources/default-iqe-cji.yaml
fixes https://github.com/RedHatInsights/bonfire/issues/328 after https://github.com/RedHatInsights/clowder/pull/855
=> Updates default iqe yaml to use env

bonfire/processor.py, bonfire/utils.py
ticket: https://issues.redhat.com/browse/RHCLOUD-28382
This is adding logic for bonfire to gather dependencies listed under the annotation `bonfire.dependencies`. This supports the need for some apps to have dependencies that are not clowdapps.
=> Add handling for bonfire.dependencies annotation

README.md
This adds a small note about the required `scope` for the Github token (classic)
=> Add mention to the required Github token scope

bonfire/elastic_logging.py
If the elasticsearch host or api-key is not provided, the telemetry sending will fail.
Now it will check and return before getting that far.
=> Check for telemetry secrets

Dockerfile, README.md, build_deploy.sh, entrypoint.sh
This adds support to build a Docker image of Bonfire with support for Openshift credentials via environment variables or Kube config files.
=> Add dockerfile for Bonfire

bonfire/bonfire.py, bonfire/namespaces.py
Adding json output option for `bonfire namespace describe`
`bonfire namespace describe -o json`
Output:
```
{
"namespace": "<value>",
"keycloak_admin_route": "<value>",
"keycloak_admin_username": "<value>",
"keycloak_admin_password": "<value>",
"clowdapps_frontends_deployed":<value>
"default_username": "<value>",
"defualt_password": "<value>"
}
```
=> added json output option for namespace describe

.github/workflows/tests.yml, .pre-commit-config.yaml, pyproject.toml
Adds a `pre-commit` config file and uses a Github action to run pre-commit with `ruff` to lint and format the code. 
Behavior changes:
- `ruff` is now used instead of `flake8`
- The pipeline will now FAIL if the linter fails, or if the formatter finds some formatting that needs to be applied.
=> feat(ci): use pre-commit

.github/workflows/tests.yml
Bumps all the GHAs that had deprecated versions and where showing up as warnings on PRs pipeline check runs
=> Bump GHAs to latest versions

.github/workflows/release.yml, .github/workflows/tests.yml
- Drop testing for unsupported Python versions
- Use ubuntu-latest for GHA runners
=> feat: drop testing on Python 3.6 and 3.7

bonfire/config.py
This is a new dependency required by landing-page-frontend. Without this new dependency - the landing page will fail to load with the newly enabled `widgetization` unleash flags (which are currently enabled on stage/prod). 
The repo is here: https://github.com/RedHatInsights/widget-layout
The deploy config is here: https://github.com/RedHatInsights/widget-layout/blob/master/deploy/frontend.yaml
CC @wise-king-sullyman
=> Update --frontend command to include widget-layout

.github/workflows/tests.yml
- Enables testing pipeline for MacOS nodes.
- Adds installer for `oc` - it was already present on Ubuntu runners, but not on MacOs ones.
- closes RHCLOUD-33785
=> test on macos

bonfire/config.py
some apps use CPU_LIMIT, CPU_REQUEST env vars, current regex expects at leas 1 character  after LIMIT/REQUEST keyword
example of env vars in sha-extractor
https://github.com/RedHatInsights/insights-sha-extractor/blob/master/deploy/clowdapp.yaml#L280-L287
=> fix: regex for trusted resource

bonfire/config.py
Changing the default reference environment to 'production' so that ephemeral envs are able to pull container images with more reliability. The stage image builds are unreliable.
=> Change default ref environment to 'insights-production'

.tekton/bonfire-pull-request.yaml, .tekton/bonfire-push.yaml
The automated reference update wont do the trick:
- https://github.com/konflux-ci/build-definitions/blob/main/task/sast-coverity-check-oci-ta/0.2/MIGRATION.md
- https://github.com/konflux-ci/build-definitions/blob/main/task/coverity-availability-check-oci-ta/0.2/MIGRATION.md
=> Manual konflux migration

README.md, bonfire/processor.py
This change is required for the Frontend operator features and is a pre-requisite for opening the migrations to the new features for HCC tenants.
By default, FEO generates a config map to the Frontend namespace(s). In stage/prod, this config map is also injected into other namespaces(s) with a deterministic name and used there. However because in EE all deployments are in the same namespace, we need to set the parameter `FRONTEND_CONTEXT_NAME` set to the `clowd_env` value in order to properly inject the config map value into specific pods (the deployment use the FRONTEND_CONTEXT_NAME env variable to get the name of the config map).
There is already one place in the processor.py where this parameter is configured however, it turns out it's needed in one additional place.
We will need a new …
=> Frontend context name ephemeral value

pyproject.toml
Update to incorporate this fix: https://github.com/RedHatInsights/ocviapy/pull/15
=> Update ocviapy to v1.3.1

.tekton/bonfire-pull-request.yaml, .tekton/bonfire-push.yaml
**Description**
The ordering of a couple tasks need to be fixed in order for the `on-pull` and `on-push` pipelines to pass.
=> fix konflux tasks

.tekton/bonfire-push.yaml
**Description**
The purpose of this PR is to update the names for the `sast-coverity-check` and `coverity-availability-check` tasks to fix the failures in the on push pipeline.
=> rearranging tasks, fixing task image name

bonfire/bonfire.py, bonfire/openshift.py, bonfire/processor.py, pyproject.toml
This PR handles 3 things:
* If NAMESPACE parameter is unset, pass it into templates during processing (similar to how we handle IMAGE_TAG)
* Fix bugs found with resource waiter:
* If there are no ClowdApps/ClowdEnvironments, the ResourceWatcher did not have enough time to fetch resources from the kubernetes API. This caused `_all_resources_ready` to think that there were no additional resources left to wait on. This fix is to fetch all resources initially with a "blocking" call before starting the background thread.
* `wait_for_all_resources` does not need to enclose `_all_resources_ready` in a `wait_for()` function. This is because `_all_resources_ready` was modified some time ago to keep lowering the timeout as it moves through each "phase". By using `wait_for` in …
=> Pass NAMESPACE param if unset, fix bugs in resource waiter

README.md, bonfire/bonfire.py, bonfire/processor.py, tests/test_processor.py
This PR adds a new CLI argument `--exclude-components`, which accepts a comma-separated list of components to be skipped by the processor so they are not deployed.
=> add cli parameter that exclude components to deploy

bonfire/qontract.py, bonfire/utils.py
Adds support for repo URLs which have the format `https://gitlab/group/subgroup/repo`
=> Handle gitlab subgroups

bonfire/qontract.py, bonfire/utils.py
For no readily apparent reason, we recently had to create a project with the
'org' part of the path as 'insights-platform/insights-operations'.  This unfortunately
causes gitlab to get confused, because it parses that as the 'insights-platform'
org and then the rest of the line doesn't match what it expects.  So we need to
URL escape the `/` in the 'org' value.
=> Make sure the 'org' value uses %2F for / when formatted into paths

bonfire/utils.py, tests/test_utils.py
In passing I found a way to simplify and improve the `hms_to_seconds`
function by using the regular expression parser to pull the hour, minute
and seconds values out directly.  I also made sure it was tested against
invalid input.
=> Simplify and improve the `hms_to_seconds` function

bonfire/namespaces.py
This PR adds `console_namespace_route` to the json output from `namespace describe`
```
$ bonfire namespace describe -o json                       
2025-08-06 12:42:03 [    INFO] [          MainThread] attempting to use current namespace from oc/kubectl context...
2025-08-06 12:42:05 [    INFO] [          MainThread] running (pid 14171): oc project -q 
2025-08-06 12:42:05 [    INFO] [           pid-14171]  |stdout| ephemeral-bckr8k
{
"namespace": "ephemeral-bckr8k",
"keycloak_admin_route": "https://ee-z2g5icl3-auth.apps.crc-eph.r9lp.p1.openshiftapps.com/auth/",
...,
"console_namespace_route": "https://console-openshift-console.apps.crc-eph.r9lp.p1.openshiftapps.com/k8s/cluster/projects/ephemeral-bckr8k"
}
```
=> add console url to namespace describe output

bonfire/processor.py
Reverts RedHatInsights/bonfire#490 ... this should cause bonfire to behave the same way it did in v6.3.0 with respect to `--component`: When `--component` is used, a component will only get deployed if it is explicitly listed in the `--component` filter. If it is not in this list, it will be skipped.
=> Revert "Don't skip dependencies when using --component"

bonfire/processor.py, tests/test_processor.py
Suppose there is an app with components A, B, and C.  And with dependencies of A', B', and C' respectively.  Prior to this patch, bonfire had an issue where the final list of items from a `process` command would be C, C', A', and B'.  The logic was such that if a component was a dependency anywhere, it would be added.
The code that caused that bug was reverted, but that left another issue where *only* listed components were added.  In that case, the final list of items would be only C.
This patch changes the logic so that only C and C' will be in the final result.
=> Only add dependencies that are descendants of requested components

bonfire/bonfire.py, bonfire/processor.py, bonfire/utils.py, tests/test_bonfire.py, tests/test_processor.py, tests/test_utils.py
In some cases, uses may want to be selective about dependency removal. For example, if some dependencies are being mocked during application testing (e.g. with WireMock), the user might still wish to retain other dependencies.
This patch changes the `--no-remove-dependency` and `--remove-dependency` options to accept a slash after a component name followed by a dependency.  If no slash follows, the component name, all dependencies will be operated on.
Obviously this creates a resolution problem if the user provides something like` --remove-dependencies foo --no-remove-dependencies foo/bar`.  The code follows two rules: "specific beats general" and "keep by default".  So in the example, the result would be the removal of all dependencies except for foo/bar.  The resolution is handled …
=> Allow fine-grained control over dependency removal

README.md, bonfire/processor.py, tests/test_processor.py
The code was erroneously limiting dependency processing to ClowdApps that match the component name exactly.  While this is often the case, it is possible for a component to contain multiple ClowdApps.
=> Fix dependency processing in components with multiple ClowdApps
