RedHatInsights/bonfire

bonfire/resources/ephemeral-clowdenvironment.yaml

- Use redis provider
- Specify resourceDefaults

Update ClowdEnv template

---

cicd/iqe_pod/create_iqe_pod.py

Add config for Automation Analytics so that the iqe tests can target the right deployment

Set up environment for Analytics

---

cicd/bootstrap.sh

If bonfire isn't on the system, install it; otherwise cd to cicd

Check for existing bonfire

---

cicd/deploy_ephemeral_env.sh

Artifacts were not collected when deploy error occurred

fix artifacts collection - handle errors

---

cicd/_common_deploy_logic.sh

- modified `jsonpath` to include `initContainers`
- changed format of `POD_CONTAINERS` to `pod_name:comma_delimited_containers` to be able to collect `initContainers` and to correctly get logs when 1 pod has multiple containers
tested with:
```bash
➜  ~ cat test.sh 
#!/bin/bash
PODS_CONTAINERS=($(oc get pods --ignore-not-found=true -n $NAMESPACE -o "jsonpath={range .items[*]}{' '}{.metadata.name}{':'}{range .spec['containers', 'initContainers'][*]}{.name}{','}"))
for pc in ${PODS_CONTAINERS[@]}; do
POD=${pc%%:*}
CONTAINERS=${pc#*:}
for c in ${CONTAINERS//,/ }; do
echo "$POD/$c" || continue
done
done
➜  ~ ./test.sh  
env-ephemeral-13-kafka-58f7d46c47-v8b58/env-ephemeral-13-kafka
env-ephemeral-13-minio-648fd6d5f8-bq5nd/env-ephemeral-13-minio …
```

Collect logs of initContainers

---

cicd/build.sh

Patchman team uses different Dockerfile name i.e. https://github.com/RedHatInsights/patchman-engine/blob/master/Dockerfile.rhel8

Allow setting different dockerfile name

---

bonfire/bonfire.py
bonfire/processor.py
cicd/_common_deploy_logic.sh
cicd/deploy_ephemeral_db.sh
cicd/deploy_ephemeral_env.sh

`-C` or `--component` option to select which components should be processed. Set via `COMPONENTS` env var in `pr_check.sh`
Do you also want error message when component does not exist?

Add option to select components for app

---

cicd/iqe_pod/create_iqe_pod.py

removing the config from here as already added in https://gitlab.cee.redhat.com/insights-qe/iqe-automation-analytics-plugin/-/blob/master/iqe_automation_analytics/conf/settings.default.yaml#L28

move config for AA to app settings file

---

README.md

Signed-off-by: Victor M <vmugicag@redhat.com>

Add example of local config to README

---

cicd/build.sh

sadly, `podman` can't do such caching
```
--cache-from string    Images to utilise as potential cache sources. The build process does not currently support caching so this is a NOOP.
```
a user would set `CACHE_FROM_LATEST_IMAGE=true` to use this feature, it tries to pull an image without tag, so it assumes `:latest` tag would exist, otherwise it won't use `--cache-from`
I didn't implemented looking for latest tagged image or latest commit hash, since there might be some private repos.

Cache image build from existing image

---

cicd/cji_smoke_test.sh

`APP_NAME` is the name of folder in app-sre
`COMPONENT_NAME` is the actual ClowdApp name - name of resourceTemplate in app-sre

Fix ClowdApp name for cji

---

cicd/cji_smoke_test.sh
cicd/deploy_ephemeral_db.sh

```console
$ git grep kill_port_fwd
cicd/cji_smoke_test.sh:function kill_port_fwd {
cicd/deploy_ephemeral_db.sh:function kill_port_fwd {
```

Drop unused function `kill_port_fwd`

---

bonfire/processor.py

This aims to fix  #109 
This processes every character found up until next `"` character, which is the next "end of field character" in a JSON string.

Patch image_tag replacement

---

cicd/_common_deploy_logic.sh

helpful for debugging if pod is restarted

Collect previous pod logs

---

bonfire/resources/ephemeral-cluster-clowdenvironment.yaml

https://issues.redhat.com/browse/RHCLOUD-16486

Bumping iqe pod req/limits

---

bonfire/qontract.py

process variable in parameters i.e. `KAFKA_URL='${KAFKA_HOST}:9092'` where `KAFKA_HOST` is defined in env file

Process env vars referenced in target vars

---

cicd/post_test_results.sh

There was a request from developers to not spam pull requests with comments. Tested it here https://github.com/RedHatInsights/compliance-backend/pull/1293

edit the test results comment if it already exists

---

bonfire/bonfire.py

Changed description of `bonfire pool` command.

Changed description of pool command.

---

cicd/post_test_results.sh

@lina-is-here :eyes: :point_left: :point_right: :eyes: 
https://docs.github.com/en/rest/pulls/pulls#list-commits-on-a-pull-request
https://docs.github.com/en/rest/commits/statuses#create-a-commit-status

Ibutsu results appear as github status for PRs

---

cicd/deploy_ephemeral_env.sh

Allow users to send an argument to the `--pool` option for the
`namespace reserve` subcommand.

Add NAMESPACE_POOL

---

bonfire/bonfire.py

Remove duplicate -f short options

---

bonfire/processor.py

Update to support new replicas field from clowdApp resource.
issue: https://github.com/RedHatInsights/bonfire/issues/278

support --single-replicas option when new replicas field is specified

---

bonfire/utils.py
process-rbac-foo.sh
tests/test_utils.py

- closes RHCLOUD-23183 and #265

fix(utils): Timeout for qontract URL connection check

---

bonfire/bonfire.py
bonfire/processor.py
bonfire/resources/default-iqe-cji.yaml

Refer :  https://github.com/RedHatInsights/clowder/pull/842 and https://github.com/RedHatInsights/clowder/pull/802
`bonfire process-iqe-cji rhsm --image-tag curiosity --plugins curiosity --selenium --parallel-enabled true --parallel-worker-count 1 --rp-args true --ibutsu-source post-stage-deploy`
```
2023-08-22 17:21:06 [    INFO] [          MainThread] processing IQE ClowdJobInvocation
{
"kind": "List",
"apiVersion": "v1",
"metadata": {},
"items": [
{
"apiVersion": "cloud.redhat.com/v1alpha1",
"kind": "ClowdJobInvocation",
"metadata": {
"name": "iqe-79c29bc4"
},
"spec": {
"appName": "rhsm",
"testing": {
"iqe": {
"debug": false,
"dynaconfEnvName": "clowder_smoke",
"filter": "",
"ibutsuSource": "post-stage-deploy",
"imageTag": "curiosity",
"marker": "",
"parallelEnabled": "true", …
```

Add new clowder iqe cji options to bonfire

---

bonfire/resources/default_config.yaml

Ticket: https://issues.redhat.com/browse/RHCLOUD-17475

Remove deprecated bonfire v2 configs

---

bonfire/elastic_logging.py

Add logs for when data transmission starts and ends successfully

ES Telemetry status logs

---

.github/workflows/release.yml

Refactor release to use trusted publishers (OIDC) with PyPi

Refactor release to support trusted publishers

---

bonfire/utils.py
pyproject.toml
tests/test_utils.py

- replaces distutils with packaging
- bugfix for when the version response cannot be parsed
- adds tests for version check logic

fix: remove deprecated distutils dependency

---

.github/workflows/tests.yml
Dockerfile

[fix: Update Python, pip and oc versions](https://github.com/RedHatInsights/bonfire/pull/423/commits/c87962db57c8f2ec050fb899bc1222b6e7e8a5ab)
- closes RHCLOUD-35460

fix: Update Python, pip and oc versions

---

pyproject.toml

Use ocviapy v1.3.0

---

bonfire/config.py

Remove settings-frontend from frontend defaults

Remove settings-frontend from frontend defaults

---

bonfire/processor.py

#482 introduced a bug...
Previously if we passed `--component` as an argument, we would still process the dependencies detected for that component. The new skip check was not taking this into consideration. This PR should fix that.

Don't skip dependencies when using --component
